### ISSUE TITLE
Can you please make a windows version

### ISSUE THREAD

**Issue by kurtfrancisco** [dyadxmachina/Distributed-Deep-Learning-with-Tensorflow#1]
Please :-)

**Comment by christianramsey** [comment]
@haohanwang23 let's look into this. @kurtfrancisco  we don't plan to do this. Section III can be used agnostic of platform. Perhaps it's just the installation of TensorFlow GPU?

**Comment by christianramsey** [comment]
@kurtfrancisco does this work for you > https://medium.com/@lmoroney_40129/installing-tensorflow-with-gpu-on-windows-10-3309fec55a00 ?
